- name: Testing Ansible
  hosts: localhost
  gather_facts: false
  vars_files:
    - variables.yml
  tasks:
    - name: Check if user 'roboshop' exists
      ansible.builtin.shell: "id roboshop"
      register: output
      ignore_errors: true

    - name: Print the output
      ansible.builtin.debug:
        msg: "Output is {{ output.stdout }}"
