- name: testing ansible
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:
    - name: check id exists or not
      ansible.builtin.command: id roboshop
      register: output
    - name: print the output
      ansible.builtin.debug:
        msg: { { output } }
