- name: testing ansible
  hosts: localhost
  tasks:
    - name: check id exists or not
      ansible.builtin.command: ls
      register: output

    - name: print the output
      ansible.builtin.debug:
        msg: "output is {{ output }}"
