- name: testing ansible
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:
    - name: outputting a command
      ansible.builtin.debug:
        msg: hi, my name is {{NAME}}, I am {{AGE}} years old and I am {{JOB}}
