- name: Test Ansible Shell in WSL
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run simple echo command
      ansible.builtin.shell: "echo 'Hello from Ansible in WSL'"
      register: test_output

    - name: Print command output
      ansible.builtin.debug:
        msg: "{{ test_output.stdout }}"
